version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - "5010:5010"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/taskmanager
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

